In [9]:
from pandas import Series,DataFrame
import pandas as pd
obj = Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [7]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2 = Series([4,7,-5,3],index=['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
obj2['a']

-5

In [11]:
obj2['d'] = 6
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [12]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [13]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [14]:
'b' in obj2

True

In [15]:
sdata={'ohio':5000,'texas':71000,'oregon':16000,'utah':5000}
obj3=Series(sdata)

In [16]:
obj3

ohio       5000
oregon    16000
texas     71000
utah       5000
dtype: int64

In [17]:
states = ['california','ohio','oregon','texas']
obj4 = Series(sdata,index=states)

In [18]:
obj4

california        NaN
ohio           5000.0
oregon        16000.0
texas         71000.0
dtype: float64

In [19]:
pd.isnull(obj4)

california     True
ohio          False
oregon        False
texas         False
dtype: bool

In [20]:
pd.notnull(obj4)

california    False
ohio           True
oregon         True
texas          True
dtype: bool

In [23]:
data = {'state':['ohio','ohio','ohio','nevada','nevada'],
        'year':[2000,2001,2002,2001,2002],
       'pop':[1.5,1.7,3.6,2.4,2.9]}
frame = DataFrame(data)

In [24]:
frame

pop   state  year
0  1.5    ohio  2000
1  1.7    ohio  2001
2  3.6    ohio  2002
3  2.4  nevada  2001
4  2.9  nevada  2002

In [26]:
DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    ohio  1.5
1  2001    ohio  1.7
2  2002    ohio  3.6
3  2001  nevada  2.4
4  2002  nevada  2.9

In [27]:
frame2 = DataFrame(data,columns=['year','state','pop','debt'],index=['one','two','three','four','five'])
frame2

year   state  pop debt
one    2000    ohio  1.5  NaN
two    2001    ohio  1.7  NaN
three  2002    ohio  3.6  NaN
four   2001  nevada  2.4  NaN
five   2002  nevada  2.9  NaN

In [28]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [29]:
frame2['state']

one        ohio
two        ohio
three      ohio
four     nevada
five     nevada
Name: state, dtype: object

In [30]:
frame2.ix['three']

D:\anaconde\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


year     2002
state    ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [31]:
frame2['debt']=16.5

In [32]:
frame2

year   state  pop  debt
one    2000    ohio  1.5  16.5
two    2001    ohio  1.7  16.5
three  2002    ohio  3.6  16.5
four   2001  nevada  2.4  16.5
five   2002  nevada  2.9  16.5

In [11]:
import numpy as np
frame2['debt'] = np.arange(5.)

NameError: name 'frame2' is not defined

In [35]:
frame2

year   state  pop  debt
one    2000    ohio  1.5   0.0
two    2001    ohio  1.7   1.0
three  2002    ohio  3.6   2.0
four   2001  nevada  2.4   3.0
five   2002  nevada  2.9   4.0

In [39]:
val = Series([-1.2,-1.5,-1.7],index=['two','four','five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    ohio  1.5   NaN
two    2001    ohio  1.7  -1.2
three  2002    ohio  3.6   NaN
four   2001  nevada  2.4  -1.5
five   2002  nevada  2.9  -1.7

In [40]:
frame2['eastern'] = frame2.state == 'ohio'

In [41]:
frame2

year   state  pop  debt  eastern
one    2000    ohio  1.5   NaN     True
two    2001    ohio  1.7  -1.2     True
three  2002    ohio  3.6   NaN     True
four   2001  nevada  2.4  -1.5    False
five   2002  nevada  2.9  -1.7    False

In [42]:
del frame2['eastern']

In [43]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [45]:
pop = {'nevada':{2001:2.4,2002:2.9},'ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [46]:
frame3 = DataFrame(pop)
frame3

nevada  ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [47]:
frame3.T

2000  2001  2002
nevada   NaN   2.4   2.9
ohio     1.5   1.7   3.6

In [49]:
pdata = {'ohio':frame3['ohio'][:-1],'nevada':frame3['nevada'][:2]}
DataFrame(pdata)

nevada  ohio
2000     NaN   1.5
2001     2.4   1.7

In [50]:
frame3.index.name = 'year';frame3.columns.name = 'state'
frame3

state  nevada  ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [51]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [52]:
frame2.values

array([[2000, 'ohio', 1.5, nan],
       [2001, 'ohio', 1.7, -1.2],
       [2002, 'ohio', 3.6, nan],
       [2001, 'nevada', 2.4, -1.5],
       [2002, 'nevada', 2.9, -1.7]], dtype=object)

In [12]:
from pandas import Series,DataFrame
obj = Series(range(3),index=['a','b','c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [57]:
index = pd.Index(np.arange(3))
index

Int64Index([0, 1, 2], dtype='int64')

In [58]:
obj = Series([1.5,-2.5,0],index=index)
obj

0    1.5
1   -2.5
2    0.0
dtype: float64

In [14]:
from pandas import Series,DataFrame
import pandas as pd
obj = Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [15]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [16]:
obj.reindex(['a','b','c','d','e'],fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [17]:
obj3 = Series(['blue','purple','yellow'],index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [18]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [23]:
import numpy as np 
frame = DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],columns=['ohio','texas','california'])
frame

ohio  texas  california
a     0      1           2
c     3      4           5
d     6      7           8

In [27]:
np.arange(9).reshape((3,3))


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
frame2 = frame.reindex(['a','b','c','d'])
frame2

ohio  texas  california
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [29]:
states = ['texas','utah','california']
frame.reindex(columns=states)

texas  utah  california
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [31]:
frame.reindex(index=['a','b','c','d'],method='ffill',columns=states)

ValueError: index must be monotonic increasing or decreasing

In [32]:
frame.ix[['a','b','c','d'],states]

D:\anaconde\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


texas  utah  california
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [34]:
obj = Series(np.arange(5.),index=['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [36]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [37]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [40]:
data = DataFrame(np.arange(16).reshape((4,4)),index=['ohio','colorado','utah','new york'],columns=['one','two','three','four'])
data

one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
utah        8    9     10    11
new york   12   13     14    15

In [41]:
data.drop(['colorado','ohio'])

one  two  three  four
utah        8    9     10    11
new york   12   13     14    15

In [42]:
data.drop('two',axis=1)

one  three  four
ohio        0      2     3
colorado    4      6     7
utah        8     10    11
new york   12     14    15

In [44]:
obj = Series(np.arange(4.),index=['a','b','c','d'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [45]:
obj['b','c']=5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [46]:
data.ix['colorado',['two','three']]

D:\anaconde\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


two      5
three    6
Name: colorado, dtype: int32

In [47]:
data.ix[data.three>5,:3]  #标签索引

one  two  three
colorado    4    5      6
utah        8    9     10
new york   12   13     14

In [48]:
s1 = Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])
s2 = Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [49]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [50]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [51]:
series2 = Series(range(3),index=['b','e','f'])
series2

b    0
e    1
f    2
dtype: int32

In [52]:
frame = DataFrame(np.random.randn(4,3),columns=list('bde'),index=['utah','ohio','texas','oregon'])
frame

b         d         e
utah    0.831846  0.043569  0.176674
ohio   -1.021503  3.093751  1.388898
texas  -0.551905 -0.272979 -0.929662
oregon  0.837304  0.269988 -0.535986

In [53]:
np.abs(frame)

b         d         e
utah    0.831846  0.043569  0.176674
ohio    1.021503  3.093751  1.388898
texas   0.551905  0.272979  0.929662
oregon  0.837304  0.269988  0.535986

In [54]:
f=lambda x:x.max() - x.min()
f

<function __main__.<lambda>>

In [55]:
frame.apply(f)

b    1.858807
d    3.366729
e    2.318560
dtype: float64

In [56]:
def f(x):
    return Series([x.min(),x.max()],index=['min','max'])

In [57]:
frame.apply(f)

b         d         e
min -1.021503 -0.272979 -0.929662
max  0.837304  3.093751  1.388898

In [59]:
format = lambda x:'%.2f' %x
frame.applymap(format)

b      d      e
utah     0.83   0.04   0.18
ohio    -1.02   3.09   1.39
texas   -0.55  -0.27  -0.93
oregon   0.84   0.27  -0.54

In [60]:
frame['e'].map(format)

utah       0.18
ohio       1.39
texas     -0.93
oregon    -0.54
Name: e, dtype: object