In [2]:
import numpy as np
import pandas as pd
from pandas import DataFrame,Series
df1 = DataFrame({'key':['b','b','a','c','a','a','b'],'data1':range(7)})

In [3]:
df2 = DataFrame({'key':['a','b','d'],'data2':range(3)})

In [4]:
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b

In [5]:
df2

data2 key
0      0   a
1      1   b
2      2   d

In [6]:
#合并两组数据（内连接）
pd.merge(df1,df2)

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [7]:
#指定主键链接
pd.merge(df1,df2,on='key')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [8]:
df3 = DataFrame({'lkey':['b','b','a','c','a','a','b'],'data1':range(7)})

In [9]:
df4 = DataFrame({'rkey':['a','b','d'],'data2':range(3)})

In [10]:
#显示两组数据
pd.merge(df3,df4,left_on='lkey',right_on='rkey')

data1 lkey  data2 rkey
0      0    b      1    b
1      1    b      1    b
2      6    b      1    b
3      2    a      0    a
4      4    a      0    a
5      5    a      0    a

In [11]:
#外链接
pd.merge(df1,df2,how='outer')

data1 key  data2
0    0.0   b    1.0
1    1.0   b    1.0
2    6.0   b    1.0
3    2.0   a    0.0
4    4.0   a    0.0
5    5.0   a    0.0
6    3.0   c    NaN
7    NaN   d    2.0

In [12]:
pd.merge(df1,df2,how='inner')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [13]:
pd.merge(df1,df2,how='left')

data1 key  data2
0      0   b    1.0
1      1   b    1.0
2      2   a    0.0
3      3   c    NaN
4      4   a    0.0
5      5   a    0.0
6      6   b    1.0

In [14]:
pd.merge(df1,df2,how='right')

data1 key  data2
0    0.0   b      1
1    1.0   b      1
2    6.0   b      1
3    2.0   a      0
4    4.0   a      0
5    5.0   a      0
6    NaN   d      2

In [15]:
df1 = DataFrame({'key':['b','b','a','c','a','b'],'data1':range(6)})

In [19]:
df2 = DataFrame({'key':['a','b','a','b','d'],'data2':range(5)})

In [20]:
pd.merge(df1,df2,how='inner')

data2 key
0      0   a
1      1   b
2      2   a
3      3   b
4      4   d

In [3]:
left= DataFrame({'key1':['foo','foo','bar'],'key2':['one','two','one'],'lval':[1,2,3]})
left

key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [4]:
right= DataFrame({'key1':['foo','foo','bar','bar'],'key2':['one','one','one','two'],'lval':[4,5,6,7]})
right

key1 key2  lval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [23]:
pd.merge(left,right,on=['key1','key2'],how='outer')

key1 key2  lval_x  lval_y
0  foo  one     1.0     4.0
1  foo  one     1.0     5.0
2  foo  two     2.0     NaN
3  bar  one     3.0     6.0
4  bar  two     NaN     7.0

In [24]:
pd.merge(left,right,on='key1')

key1 key2_x  lval_x key2_y  lval_y
0  foo    one       1    one       4
1  foo    one       1    one       5
2  foo    two       2    one       4
3  foo    two       2    one       5
4  bar    one       3    one       6
5  bar    one       3    two       7

In [25]:
pd.merge(left,right,on='key1',suffixes=('_left','_right'))

key1 key2_left  lval_left key2_right  lval_right
0  foo       one          1        one           4
1  foo       one          1        one           5
2  foo       two          2        one           4
3  foo       two          2        one           5
4  bar       one          3        one           6
5  bar       one          3        two           7

In [5]:
left1 = DataFrame({'key':['a','b','a','a','b','c'],'value':range(6)})

In [6]:
right1=DataFrame({'group_val':[3.5,7]},index=['a','b'])

In [7]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [8]:
right1

group_val
a        3.5
b        7.0

In [9]:
pd.merge(left1,right1,left_on='key',right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [10]:
pd.merge(left1,right1,left_on='key',right_index=True,how='outer')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [11]:
lefth = DataFrame({'key1':['ohio','ohio','ohio','nevada','nevada'],'key2':[2000,2001,2002,2001,2002],'data':np.arange(5.)})

In [12]:
righth = DataFrame(np.arange(12).reshape((6,2)),index=[['nevada','nevada','ohio','ohio','ohio','ohio'],
                                                       [2001,2000,2000,2000,2001,2002]],columns=['event1','event2'])

In [13]:
lefth

data    key1  key2
0   0.0    ohio  2000
1   1.0    ohio  2001
2   2.0    ohio  2002
3   3.0  nevada  2001
4   4.0  nevada  2002

In [14]:
righth

event1  event2
nevada 2001       0       1
       2000       2       3
ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [15]:
pd.merge(lefth,righth,left_on=['key1','key2'],right_index=True)

data    key1  key2  event1  event2
0   0.0    ohio  2000       4       5
0   0.0    ohio  2000       6       7
1   1.0    ohio  2001       8       9
2   2.0    ohio  2002      10      11
3   3.0  nevada  2001       0       1

In [16]:
pd.merge(lefth,righth,left_on=['key1','key2'],right_index=True,how='outer')

data    key1  key2  event1  event2
0   0.0    ohio  2000     4.0     5.0
0   0.0    ohio  2000     6.0     7.0
1   1.0    ohio  2001     8.0     9.0
2   2.0    ohio  2002    10.0    11.0
3   3.0  nevada  2001     0.0     1.0
4   4.0  nevada  2002     NaN     NaN
4   NaN  nevada  2000     2.0     3.0

In [17]:
left2 =DataFrame([[1.,2.],[3.,4.],[5.,6.]],index=['a','c','e'],columns=['ohio','nevada'])

In [22]:
right2 = DataFrame([[7.,8.],[9.,10.],[11.,12.],[13,14]],index=['b','c','d','e'],columns=['missouri','alabama'])

In [20]:
left2

ohio  nevada
a   1.0     2.0
c   3.0     4.0
e   5.0     6.0

In [23]:
right2

missouri  alabama
b       7.0      8.0
c       9.0     10.0
d      11.0     12.0
e      13.0     14.0

In [24]:
pd.merge(left2,right2,how='outer',left_index=True,right_index=True)

ohio  nevada  missouri  alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [25]:
left2.join(right2,how='outer')

ohio  nevada  missouri  alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [28]:
left1.join(right1,on='key')

key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

In [29]:
another = DataFrame([[7.,8.],[9.,10.],[11.,12.],[16.,17.]],index = ['a','c','e','f'],columns=['new york','oregon'])

In [30]:
left2.join([right2,another])

ohio  nevada  missouri  alabama  new york  oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
c   3.0     4.0       9.0     10.0       9.0    10.0
e   5.0     6.0      13.0     14.0      11.0    12.0

In [31]:
left2.join([right2,another],how='outer')

ohio  nevada  missouri  alabama  new york  oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
b   NaN     NaN       7.0      8.0       NaN     NaN
c   3.0     4.0       9.0     10.0       9.0    10.0
d   NaN     NaN      11.0     12.0       NaN     NaN
e   5.0     6.0      13.0     14.0      11.0    12.0
f   NaN     NaN       NaN      NaN      16.0    17.0

In [32]:
arr=np.arange(12).reshape((3,4))

In [33]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
np.concatenate([arr,arr],axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [40]:
s1=Series([0,1],index=['a','b'])

In [41]:
s2=Series([2,3,4],index=['c','d','e'])

In [42]:
s3=Series([5,6],index=['f','g'])

In [43]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [44]:
pd.concat([s1,s2,s3],axis=1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [47]:
s4=pd.concat([s1*5,s3])
s4

a    0
b    5
f    5
g    6
dtype: int64

In [46]:
pd.concat([s1,s4],axis=1)

0  1
a  0.0  0
b  1.0  5
f  NaN  5
g  NaN  6

In [48]:
pd.concat([s1,s4],axis=1,join='inner')

0  1
a  0  0
b  1  5

In [49]:
pd.concat([s1,s4],axis=1,join_axes=[['a','c','b','e']])

0    1
a  0.0  0.0
c  NaN  NaN
b  1.0  5.0
e  NaN  NaN

In [52]:
result = pd.concat([s1,s1,s3],keys=['one','two','three'])

In [53]:
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [54]:
 pd.concat([s1,s1,s3],axis=1,keys=['one','two','three'])

one  two  three
a  0.0  0.0    NaN
b  1.0  1.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [55]:
df1=DataFrame(np.arange(6).reshape(3,2),index=['a','b','c'],columns=['one','two'])

In [56]:
df2=DataFrame(5+np.arange(4).reshape(2,2),index=['a','c'],columns=['three','four'])

In [57]:
pd.concat([df1,df2],axis=1,keys=['level1','level2'])

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [59]:
pd.concat({'level1':df1,'level2':df2},axis=1)

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [60]:
pd.concat([df1,df2],axis=1,keys=['level1','level2'],names=['upper','lower'])

upper level1     level2     
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

In [1]:
import numpy as np 
import pandas as pd
from pandas import Series,DataFrame
a=Series([np.nan,2.5,np.nan,3.5,4.5,np.nan],index=['f','e','d','c','b','a'])

In [3]:
b=Series(np.arange(len(a),dtype=np.float64),index=['f','e','d','c','b','a'])

In [4]:
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [5]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    5.0
dtype: float64

In [8]:
b[-1]=np.nan
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [9]:
np.where(pd.isnull(a),b,a)

array([ 0. ,  2.5,  2. ,  3.5,  4.5,  nan])

In [10]:
b[:-2]

f    0.0
e    1.0
d    2.0
c    3.0
dtype: float64

In [11]:
a[2:]

d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [13]:
b[:-2].combine_first(a[2:])

a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

In [14]:
df1 = DataFrame({'a':[1.,np.nan,5.,np.nan],'b':[np.nan,2.,np.nan,6.],'c':range(2,18,4)})

In [16]:
df2= DataFrame({'a':[5.,4.,np.nan,3.,7.],'b':[np.nan,3.,4.,6.,8.]})

In [17]:
df1

a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [18]:
df2

a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [19]:
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

In [20]:
data = DataFrame(np.arange(6).reshape((2,3)),index=pd.Index(['ohio','colorado'],name='state'),
                 columns=pd.Index(['one','two','three'],name='number'))

In [21]:
data

number    one  two  three
state                    
ohio        0    1      2
colorado    3    4      5

In [22]:
result=data.stack()

In [23]:
result

state     number
ohio      one       0
          two       1
          three     2
colorado  one       3
          two       4
          three     5
dtype: int32

In [24]:
result.unstack()

number    one  two  three
state                    
ohio        0    1      2
colorado    3    4      5

In [25]:
result.unstack(0)

state   ohio  colorado
number                
one        0         3
two        1         4
three      2         5

In [27]:
result.unstack('state')

state   ohio  colorado
number                
one        0         3
two        1         4
three      2         5

In [28]:
s1=Series([0,1,2,3],index=['a','b','c','d'])

In [31]:
s2=Series((4,5,6),index=['c','d','e'])

In [34]:
data2=pd.concat([s1,s2],keys=['one','two'])
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: int64

In [35]:
data2.unstack()

a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0

In [36]:
data2.unstack().stack()

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
two  c    4.0
     d    5.0
     e    6.0
dtype: float64

In [37]:
data2.unstack().stack(dropna=False)

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
     e    NaN
two  a    NaN
     b    NaN
     c    4.0
     d    5.0
     e    6.0
dtype: float64

In [38]:
df=DataFrame({'left':result,'right':result+5},columns=pd.Index(['left','right'],name='side'))

In [39]:
df

side             left  right
state    number             
ohio     one        0      5
         two        1      6
         three      2      7
colorado one        3      8
         two        4      9
         three      5     10

In [40]:
df.unstack('state')

side   left          right         
state  ohio colorado  ohio colorado
number                             
one       0        3     5        8
two       1        4     6        9
three     2        5     7       10

In [41]:
df.unstack('state').stack('side')

state         colorado  ohio
number side                 
one    left          3     0
       right         8     5
two    left          4     1
       right         9     6
three  left          5     2
       right        10     7

In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
data = DataFrame({'k1':['one']*3 + ['two']*4,'k2':[1,1,2,3,3,4,4]})

In [7]:
data

k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [2]:
#duplicated方法返回一个布尔型series,表示各行是否是重复行
data.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [3]:
#drop_duplicates返回一个移除了重复行的dataframe
data.drop_duplicates()

k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [10]:
data['v1'] = range(7)

In [4]:
data.drop_duplicates(['k1'])

k1  k2
0  one   1
3  two   3

In [5]:
#duplicated和drop_duplicates默认保留的是第一个出现的值组合，传入tkeep='last'则保留最后一个
data.drop_duplicates(['k1','k2'],keep='last')

k1  k2
1  one   1
2  one   2
4  two   3
6  two   4

In [6]:
data = DataFrame({'food':['bacon','pulled pork','bacon','pastrami','corned beef','bacon',
                         'pastrami','honey ham','nova lox'],'ounces':
                  [4,3,12,6,7.5,8,3,5,6]})

In [19]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [7]:
meat_to_animal = {'bacon':'pig','pulled pork':'pig','pastrami':'cow','corned beef':'cow',
                 'corned beef':'cow','honey ham':'pjg','nova lox':'salmon'}

In [8]:
#map方法接受一个函数或含有映射关系的字典型对象
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)

In [9]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pjg
8     nova lox     6.0  salmon

In [10]:
data['food'].map(lambda x:meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pjg
8    salmon
Name: food, dtype: object

In [11]:
data = Series([1,-999,2,-999,-1000,3])

In [12]:
data

0       1
1    -999
2       2
3    -999
4   -1000
5       3
dtype: int64

In [14]:
#将-999用nan替换
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [15]:
data.replace([-999,-1000],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [16]:
data.replace([-999,-1000],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [18]:
data.replace({-999:np.nan,-1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [20]:
data = DataFrame(np.arange(12).reshape((3,4)),index=['ohio','colorado','new york'],columns=['one','two','three','four'])

In [21]:
data

one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
new york    8    9     10    11

In [22]:
data.index.map(str.upper)


Index(['OHIO', 'COLORADO', 'NEW YORK'], dtype='object')

In [23]:
data.index = data.index.map(str.upper)

In [24]:
data

one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [25]:
data.rename(index=str.title,columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [26]:
data.rename(index={'OHIO':'INDIANA'},columns={'three':'peekaboo'})

one  two  peekaboo  four
INDIANA     0    1         2     3
COLORADO    4    5         6     7
NEW YORK    8    9        10    11

In [27]:
data.rename(index={'OHIO':'INDIANA'},inplace=True)

In [28]:
data

one  two  three  four
INDIANA     0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [30]:
ages=(20,22,25,27,21,23,37,31,61,45,41,32)

In [31]:
bins=[18,25,35,60,100]

In [32]:
cats=pd.cut(ages,bins)

In [33]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [35]:
cats.labels

E:\anaconda3-5.0.1\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 'labels' is deprecated. Use 'codes' instead
  """Entry point for launching an IPython kernel.


array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [37]:
#计数
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [38]:
pd.cut(ages,[18,26,36,61,100],right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [39]:
group_names=['youth','youngadult','middleaged','senior']

In [40]:
pd.cut(ages,bins,labels=group_names)

[youth, youth, youth, youngadult, youth, ..., youngadult, senior, middleaged, middleaged, youngadult]
Length: 12
Categories (4, object): [youth < youngadult < middleaged < senior]

In [41]:
data=np.random.rand(20)

In [42]:
data

array([ 0.79528538,  0.70586429,  0.2509606 ,  0.85815699,  0.7536345 ,
        0.15670818,  0.96229517,  0.36554671,  0.8778097 ,  0.70245363,
        0.58616589,  0.35497738,  0.04245403,  0.34584103,  0.1917043 ,
        0.88432589,  0.31862779,  0.23259033,  0.12689921,  0.90009849])

In [43]:
pd.cut(data,4,precision=2)

[(0.73, 0.96], (0.5, 0.73], (0.042, 0.27], (0.73, 0.96], (0.73, 0.96], ..., (0.73, 0.96], (0.27, 0.5], (0.042, 0.27], (0.042, 0.27], (0.73, 0.96]]
Length: 20
Categories (4, interval[float64]): [(0.042, 0.27] < (0.27, 0.5] < (0.5, 0.73] < (0.73, 0.96]]

In [44]:
data=np.random.randn(1000)#正态分布

In [48]:
cats=pd.qcut(data,4)#按四分位数进行切割

In [49]:
cats

[(-0.626, 0.0118], (-0.626, 0.0118], (0.707, 3.381], (-3.611, -0.626], (0.707, 3.381], ..., (0.0118, 0.707], (0.0118, 0.707], (0.707, 3.381], (0.0118, 0.707], (0.707, 3.381]]
Length: 1000
Categories (4, interval[float64]): [(-3.611, -0.626] < (-0.626, 0.0118] < (0.0118, 0.707] < (0.707, 3.381]]

In [50]:
pd.value_counts(cats)

(0.707, 3.381]      250
(0.0118, 0.707]     250
(-0.626, 0.0118]    250
(-3.611, -0.626]    250
dtype: int64

In [51]:
pd.qcut(data,[0,0.1,0.5,0.9,1])

[(-1.202, 0.0118], (-1.202, 0.0118], (0.0118, 1.249], (-1.202, 0.0118], (0.0118, 1.249], ..., (0.0118, 1.249], (0.0118, 1.249], (0.0118, 1.249], (0.0118, 1.249], (1.249, 3.381]]
Length: 1000
Categories (4, interval[float64]): [(-3.611, -1.202] < (-1.202, 0.0118] < (0.0118, 1.249] < (1.249, 3.381]]

In [52]:
np.random.seed(12345)

In [53]:
data= DataFrame(np.random.randn(1000,4))

In [54]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528

In [57]:
col=data[3]
col

0     -0.555730
1      0.281746
2     -1.296221
3      0.886429
4     -0.438570
5     -1.021228
6      0.523772
7     -0.831154
8      0.560145
9      0.332883
10    -0.970736
11    -0.753887
12     0.246674
13    -0.919262
14    -0.660524
15     0.670216
16    -2.304234
17     1.074623
18    -0.503087
19     0.222896
20     0.433610
21     0.850591
22     2.169461
23     0.795253
24     0.152677
25    -0.929006
26     0.980928
27     0.457002
28    -0.402827
29    -1.648985
         ...   
970   -1.460094
971    0.132262
972   -1.091849
973   -1.243078
974   -0.521155
975   -0.307670
976    1.381155
977    0.075798
978    0.102469
979    1.120895
980   -0.285176
981    0.053410
982    0.233619
983    0.604880
984   -0.335099
985    1.367213
986   -0.512542
987   -1.050942
988   -0.387002
989    1.642339
990    1.336648
991    0.153988
992   -1.466596
993    1.101972
994    0.604072
995    1.653126
996   -1.502870
997    0.133304
998   -0.303340
999    0.882755
Name: 3, Length: 1000, d

In [56]:
col[np.abs(col)>3]

97     3.927528
305   -3.399312
400   -3.745356
Name: 3, dtype: float64

In [58]:
data[(np.abs(data)>3).any(1)]

0         1         2         3
5   -0.539741  0.476985  3.248944 -1.021228
97  -0.774363  0.552936  0.106061  3.927528
102 -0.655054 -0.565230  3.176873  0.959533
305 -2.315555  0.457246 -0.025907 -3.399312
324  0.050188  1.951312  3.260383  0.963301
400  0.146326  0.508391 -0.196713 -3.745356
499 -0.293333 -0.242459 -3.056990  1.918403
523 -3.428254 -0.296336 -0.439938 -0.867165
586  0.275144  1.179227 -3.184377  1.369891
808 -0.362528 -3.548824  1.553205 -2.186301
900  3.366626 -2.372214  0.851010  1.332846

In [59]:
data[np.abs(data)>3]=np.sign(data)*3

In [60]:
data

0         1         2         3
0   -0.204708  0.478943 -0.519439 -0.555730
1    1.965781  1.393406  0.092908  0.281746
2    0.769023  1.246435  1.007189 -1.296221
3    0.274992  0.228913  1.352917  0.886429
4   -2.001637 -0.371843  1.669025 -0.438570
5   -0.539741  0.476985  3.000000 -1.021228
6   -0.577087  0.124121  0.302614  0.523772
7    0.000940  1.343810 -0.713544 -0.831154
8   -2.370232 -1.860761 -0.860757  0.560145
9   -1.265934  0.119827 -1.063512  0.332883
10  -2.359419 -0.199543 -1.541996 -0.970736
11  -1.307030  0.286350  0.377984 -0.753887
12   0.331286  1.349742  0.069877  0.246674
13  -0.011862  1.004812  1.327195 -0.919262
14  -1.549106  0.022185  0.758363 -0.660524
15   0.862580 -0.010032  0.050009  0.670216
16   0.852965 -0.955869 -0.023493 -2.304234
17  -0.652469 -1.218302 -1.332610  1.074623
18   0.723642  0.690002  1.001543 -0.503087
19  -0.622274 -0.921169 -0.726213  0.222896
20   0.051316 -1.157719  0.816707  0.433610
21   1.010737  1.824875 -0.997518  0.850591
22  -0.131578  0.912414  0.188211  2.169461
23  -0.114928  2.003697  0.029610  0.795253
24   0.118110 -0.748532  0.584970  0.152677
25  -1.565657 -0.562540 -0.032664 -0.929006
26  -0.482573 -0.036264  1.095390  0.980928
27  -0.589488  1.581700 -0.528735  0.457002
28   0.929969 -1.569271 -1.022487 -0.402827
29   0.220487 -0.193401  0.669158 -1.648985
..        ...       ...       ...       ...
970  1.140886  0.113279  0.206782 -1.460094
971 -1.523554 -0.590572 -0.324064  0.132262
972  0.097878  1.244456 -0.048534 -1.091849
973 -0.738296  0.115881  0.016253 -1.243078
974 -1.969172 -1.141360  0.405558 -0.521155
975 -0.813280 -0.461413  1.159668 -0.307670
976  0.669147  0.397355  0.612537  1.381155
977 -0.042541  1.182125  0.153036  0.075798
978  0.615651 -1.992291  0.963044  0.102469
979  0.359400  0.355787 -0.799366  1.120895
980 -0.261844 -0.474138 -0.112021 -0.285176
981 -0.136429  1.285628  0.753586  0.053410
982 -0.355393  0.790731  1.274794  0.233619
983 -1.316005  1.396082  0.336700  0.604880
984  0.675317 -0.060329  1.801953 -0.335099
985 -0.754114  0.650691  0.365401  1.367213
986 -0.105654 -0.001860  0.316802 -0.512542
987 -0.052736 -0.457225  2.452835 -1.050942
988 -0.172078  0.853049 -0.356263 -0.387002
989  0.881601  1.067288  1.079688  1.642339
990 -0.103672 -0.882949 -0.197357  1.336648
991  0.926782 -0.527103  0.633763  0.153988
992 -0.527754  0.815104 -0.677870 -1.466596
993  0.957144  0.377342 -0.383241  1.101972
994  1.221058 -0.326481  0.750008  0.604072
995  1.089085  0.251232 -1.451985  1.653126
996 -0.478509 -0.010663 -1.060881 -1.502870
997 -1.946267  1.013592  0.037333  0.133304
998 -1.293122 -0.322542 -0.782960 -0.303340
999  0.089987  0.292291  1.177706  0.882755

[1000 rows x 4 columns]

In [61]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067623     0.068473     0.025153    -0.002081
std       0.995485     0.990253     1.003977     0.989736
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.000000     2.653656     3.000000     3.000000

In [64]:
df=DataFrame(np.arange(5*4).reshape(5,4))
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [65]:
sampler=np.random.permutation(5)
sampler

array([1, 3, 4, 0, 2])

In [66]:
df.take(sampler)

0   1   2   3
1   4   5   6   7
3  12  13  14  15
4  16  17  18  19
0   0   1   2   3
2   8   9  10  11

In [67]:
df.take(np.random.permutation(len(df))[:3])

0   1   2   3
1   4   5   6   7
3  12  13  14  15
0   0   1   2   3

In [71]:
bag=np.array([5,7,-1,6,4])

In [72]:
sampler=np.random.randint(0,len(bag),size=10)

In [73]:
sampler

array([1, 1, 2, 3, 0, 1, 2, 2, 3, 2])

In [74]:
draws=bag.take(sampler)

In [75]:
draws

array([ 7,  7, -1,  6,  5,  7, -1, -1,  6, -1])

In [76]:
df=DataFrame({'key':['b','b','a','c','a','b'],'data1':range(6)})

In [77]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [78]:
dummies=pd.get_dummies(df['key'],prefix='key')

In [79]:
df_with_dummy = df[['data1']].join(dummies)

In [80]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [83]:
values=np.random.rand(10)

In [84]:
values

array([ 0.85564381,  0.58743194,  0.15314009,  0.5950288 ,  0.38508854,
        0.44740483,  0.32410284,  0.92360521,  0.51923163,  0.53105727])

In [85]:
bins=[0,0.2,0.4,0.6,0.8,1]

In [86]:
pd.get_dummies(pd.cut(values,bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           0           1           0           0
2           1           0           0           0           0
3           0           0           1           0           0
4           0           1           0           0           0
5           0           0           1           0           0
6           0           1           0           0           0
7           0           0           0           0           1
8           0           0           1           0           0
9           0           0           1           0           0

In [87]:
values=np.random.rand(10)

In [88]:
values

array([ 0.17332397,  0.34263784,  0.1083731 ,  0.9276808 ,  0.18307257,
        0.13446399,  0.8195306 ,  0.88401981,  0.25354715,  0.58577873])

In [89]:
bins=[0,0.2,0.4,0.6,0.8,1]
pd.get_dummies(pd.cut(values,bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           1           0           0           0           0
1           0           1           0           0           0
2           1           0           0           0           0
3           0           0           0           0           1
4           1           0           0           0           0
5           1           0           0           0           0
6           0           0           0           0           1
7           0           0           0           0           1
8           0           1           0           0           0
9           0           0           1           0           0

In [90]:
val='a,b, guido'

In [91]:
val.split(',')

['a', 'b', ' guido']

In [92]:
#split结合strip(用于修剪空白符（包括换行符)）一起使用
pieces=[x.strip() for x in val.split(',')]

In [93]:
pieces

['a', 'b', 'guido']

In [94]:
first,second,third=pieces

In [95]:
first+'::'+second+'::'+third

'a::b::guido'

In [96]:
'::'.join(pieces)

'a::b::guido'

In [97]:
'guido' in val

True

In [98]:
val.index(',')

1

In [99]:
val.find(':')

-1

In [100]:
#指定子串出现的次数
val.count(',')

2

In [101]:
val.replace(',','::')

'a::b:: guido'

In [102]:
val.replace(',','')

'ab guido'

In [103]:
import re
text = "foo    bar\t baz   \tqux"

In [104]:
#调用re.split('\s+',text)时，正则表达式会先被编译，然后再在text上调用split方法
re.split('\s+',text)

['foo', 'bar', 'baz', 'qux']

In [105]:
regex=re.compile('\s+')

In [106]:
regex.findall(text)

['    ', '\t ', '   \t']

In [107]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [108]:
text="""dave dave@google.com
steve steve@gmail.com
rob rob@gmail.com
ryan ryan@yahoo.com"""

In [114]:
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

In [113]:
regex=re.compile(pattern,flags=re.IGNORECASE)

error: bad character range O-9 at position 19

In [115]:
regex.findall(text)

[' ', '\n', ' ', '\n', ' ', '\n', ' ']

In [119]:
m=regex.search(text)

In [118]:
m

<_sre.SRE_Match object; span=(4, 5), match=' '>

In [120]:
text[m.start():m.end()]

' '

In [123]:
print(regex.sub('REDACTED',text))

daveREDACTEDdave@google.comREDACTEDsteveREDACTEDsteve@gmail.comREDACTEDrobREDACTEDrob@gmail.comREDACTEDryanREDACTEDryan@yahoo.com


In [124]:
m=regex.match('wesm@bright.net')

In [127]:
data={'dave':'dave@google.com','steve':'steve@gmail.com','rob':'rob@gmail.com','ryan':'ryan@yahoo.com','wes':np.nan}

In [128]:
data=Series(data)

In [129]:
data

dave     dave@google.com
rob        rob@gmail.com
ryan      ryan@yahoo.com
steve    steve@gmail.com
wes                  NaN
dtype: object

In [130]:
data.isnull()

dave     False
rob      False
ryan     False
steve    False
wes       True
dtype: bool

In [131]:
data.str.contains('gmail')

dave     False
rob       True
ryan     False
steve     True
wes        NaN
dtype: object

In [132]:
pattern

'[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,4}'