In [2]:
import numpy as np
import pandas as pd
from pandas import DataFrame,Series
df1 = DataFrame({'key':['b','b','a','c','a','a','b'],'data1':range(7)})

In [3]:
df2 = DataFrame({'key':['a','b','d'],'data2':range(3)})

In [4]:
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b

In [5]:
df2

data2 key
0      0   a
1      1   b
2      2   d

In [6]:
#合并两组数据（内连接）
pd.merge(df1,df2)

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [7]:
#指定主键链接
pd.merge(df1,df2,on='key')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [8]:
df3 = DataFrame({'lkey':['b','b','a','c','a','a','b'],'data1':range(7)})

In [9]:
df4 = DataFrame({'rkey':['a','b','d'],'data2':range(3)})

In [10]:
#显示两组数据
pd.merge(df3,df4,left_on='lkey',right_on='rkey')

data1 lkey  data2 rkey
0      0    b      1    b
1      1    b      1    b
2      6    b      1    b
3      2    a      0    a
4      4    a      0    a
5      5    a      0    a

In [11]:
#外链接
pd.merge(df1,df2,how='outer')

data1 key  data2
0    0.0   b    1.0
1    1.0   b    1.0
2    6.0   b    1.0
3    2.0   a    0.0
4    4.0   a    0.0
5    5.0   a    0.0
6    3.0   c    NaN
7    NaN   d    2.0

In [12]:
pd.merge(df1,df2,how='inner')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [13]:
pd.merge(df1,df2,how='left')

data1 key  data2
0      0   b    1.0
1      1   b    1.0
2      2   a    0.0
3      3   c    NaN
4      4   a    0.0
5      5   a    0.0
6      6   b    1.0

In [14]:
pd.merge(df1,df2,how='right')

data1 key  data2
0    0.0   b      1
1    1.0   b      1
2    6.0   b      1
3    2.0   a      0
4    4.0   a      0
5    5.0   a      0
6    NaN   d      2

In [15]:
df1 = DataFrame({'key':['b','b','a','c','a','b'],'data1':range(6)})

In [19]:
df2 = DataFrame({'key':['a','b','a','b','d'],'data2':range(5)})

In [20]:
pd.merge(df1,df2,how='inner')

data2 key
0      0   a
1      1   b
2      2   a
3      3   b
4      4   d

In [3]:
left= DataFrame({'key1':['foo','foo','bar'],'key2':['one','two','one'],'lval':[1,2,3]})
left

key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [4]:
right= DataFrame({'key1':['foo','foo','bar','bar'],'key2':['one','one','one','two'],'lval':[4,5,6,7]})
right

key1 key2  lval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [23]:
pd.merge(left,right,on=['key1','key2'],how='outer')

key1 key2  lval_x  lval_y
0  foo  one     1.0     4.0
1  foo  one     1.0     5.0
2  foo  two     2.0     NaN
3  bar  one     3.0     6.0
4  bar  two     NaN     7.0

In [24]:
pd.merge(left,right,on='key1')

key1 key2_x  lval_x key2_y  lval_y
0  foo    one       1    one       4
1  foo    one       1    one       5
2  foo    two       2    one       4
3  foo    two       2    one       5
4  bar    one       3    one       6
5  bar    one       3    two       7

In [25]:
pd.merge(left,right,on='key1',suffixes=('_left','_right'))

key1 key2_left  lval_left key2_right  lval_right
0  foo       one          1        one           4
1  foo       one          1        one           5
2  foo       two          2        one           4
3  foo       two          2        one           5
4  bar       one          3        one           6
5  bar       one          3        two           7

In [5]:
left1 = DataFrame({'key':['a','b','a','a','b','c'],'value':range(6)})

In [6]:
right1=DataFrame({'group_val':[3.5,7]},index=['a','b'])

In [7]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [8]:
right1

group_val
a        3.5
b        7.0

In [9]:
pd.merge(left1,right1,left_on='key',right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [10]:
pd.merge(left1,right1,left_on='key',right_index=True,how='outer')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [11]:
lefth = DataFrame({'key1':['ohio','ohio','ohio','nevada','nevada'],'key2':[2000,2001,2002,2001,2002],'data':np.arange(5.)})

In [12]:
righth = DataFrame(np.arange(12).reshape((6,2)),index=[['nevada','nevada','ohio','ohio','ohio','ohio'],
                                                       [2001,2000,2000,2000,2001,2002]],columns=['event1','event2'])

In [13]:
lefth

data    key1  key2
0   0.0    ohio  2000
1   1.0    ohio  2001
2   2.0    ohio  2002
3   3.0  nevada  2001
4   4.0  nevada  2002

In [14]:
righth

event1  event2
nevada 2001       0       1
       2000       2       3
ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [15]:
pd.merge(lefth,righth,left_on=['key1','key2'],right_index=True)

data    key1  key2  event1  event2
0   0.0    ohio  2000       4       5
0   0.0    ohio  2000       6       7
1   1.0    ohio  2001       8       9
2   2.0    ohio  2002      10      11
3   3.0  nevada  2001       0       1

In [16]:
pd.merge(lefth,righth,left_on=['key1','key2'],right_index=True,how='outer')

data    key1  key2  event1  event2
0   0.0    ohio  2000     4.0     5.0
0   0.0    ohio  2000     6.0     7.0
1   1.0    ohio  2001     8.0     9.0
2   2.0    ohio  2002    10.0    11.0
3   3.0  nevada  2001     0.0     1.0
4   4.0  nevada  2002     NaN     NaN
4   NaN  nevada  2000     2.0     3.0

In [17]:
left2 =DataFrame([[1.,2.],[3.,4.],[5.,6.]],index=['a','c','e'],columns=['ohio','nevada'])

In [22]:
right2 = DataFrame([[7.,8.],[9.,10.],[11.,12.],[13,14]],index=['b','c','d','e'],columns=['missouri','alabama'])

In [20]:
left2

ohio  nevada
a   1.0     2.0
c   3.0     4.0
e   5.0     6.0

In [23]:
right2

missouri  alabama
b       7.0      8.0
c       9.0     10.0
d      11.0     12.0
e      13.0     14.0

In [24]:
pd.merge(left2,right2,how='outer',left_index=True,right_index=True)

ohio  nevada  missouri  alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [25]:
left2.join(right2,how='outer')

ohio  nevada  missouri  alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [28]:
left1.join(right1,on='key')

key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

In [29]:
another = DataFrame([[7.,8.],[9.,10.],[11.,12.],[16.,17.]],index = ['a','c','e','f'],columns=['new york','oregon'])

In [30]:
left2.join([right2,another])

ohio  nevada  missouri  alabama  new york  oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
c   3.0     4.0       9.0     10.0       9.0    10.0
e   5.0     6.0      13.0     14.0      11.0    12.0

In [31]:
left2.join([right2,another],how='outer')

ohio  nevada  missouri  alabama  new york  oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
b   NaN     NaN       7.0      8.0       NaN     NaN
c   3.0     4.0       9.0     10.0       9.0    10.0
d   NaN     NaN      11.0     12.0       NaN     NaN
e   5.0     6.0      13.0     14.0      11.0    12.0
f   NaN     NaN       NaN      NaN      16.0    17.0

In [32]:
arr=np.arange(12).reshape((3,4))

In [33]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
np.concatenate([arr,arr],axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [40]:
s1=Series([0,1],index=['a','b'])

In [41]:
s2=Series([2,3,4],index=['c','d','e'])

In [42]:
s3=Series([5,6],index=['f','g'])

In [43]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [44]:
pd.concat([s1,s2,s3],axis=1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [47]:
s4=pd.concat([s1*5,s3])
s4

a    0
b    5
f    5
g    6
dtype: int64

In [46]:
pd.concat([s1,s4],axis=1)

0  1
a  0.0  0
b  1.0  5
f  NaN  5
g  NaN  6

In [48]:
pd.concat([s1,s4],axis=1,join='inner')

0  1
a  0  0
b  1  5

In [49]:
pd.concat([s1,s4],axis=1,join_axes=[['a','c','b','e']])

0    1
a  0.0  0.0
c  NaN  NaN
b  1.0  5.0
e  NaN  NaN

In [52]:
result = pd.concat([s1,s1,s3],keys=['one','two','three'])

In [53]:
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [54]:
 pd.concat([s1,s1,s3],axis=1,keys=['one','two','three'])

one  two  three
a  0.0  0.0    NaN
b  1.0  1.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [55]:
df1=DataFrame(np.arange(6).reshape(3,2),index=['a','b','c'],columns=['one','two'])

In [56]:
df2=DataFrame(5+np.arange(4).reshape(2,2),index=['a','c'],columns=['three','four'])

In [57]:
pd.concat([df1,df2],axis=1,keys=['level1','level2'])

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [59]:
pd.concat({'level1':df1,'level2':df2},axis=1)

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [60]:
pd.concat([df1,df2],axis=1,keys=['level1','level2'],names=['upper','lower'])

upper level1     level2     
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

In [1]:
import numpy as np 
import pandas as pd
from pandas import Series,DataFrame
a=Series([np.nan,2.5,np.nan,3.5,4.5,np.nan],index=['f','e','d','c','b','a'])

In [3]:
b=Series(np.arange(len(a),dtype=np.float64),index=['f','e','d','c','b','a'])

In [4]:
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [5]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    5.0
dtype: float64

In [8]:
b[-1]=np.nan
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [9]:
np.where(pd.isnull(a),b,a)

array([ 0. ,  2.5,  2. ,  3.5,  4.5,  nan])

In [10]:
b[:-2]

f    0.0
e    1.0
d    2.0
c    3.0
dtype: float64

In [11]:
a[2:]

d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [13]:
b[:-2].combine_first(a[2:])

a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

In [14]:
df1 = DataFrame({'a':[1.,np.nan,5.,np.nan],'b':[np.nan,2.,np.nan,6.],'c':range(2,18,4)})

In [16]:
df2= DataFrame({'a':[5.,4.,np.nan,3.,7.],'b':[np.nan,3.,4.,6.,8.]})

In [17]:
df1

a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [18]:
df2

a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [19]:
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

In [20]:
data = DataFrame(np.arange(6).reshape((2,3)),index=pd.Index(['ohio','colorado'],name='state'),
                 columns=pd.Index(['one','two','three'],name='number'))

In [21]:
data

number    one  two  three
state                    
ohio        0    1      2
colorado    3    4      5

In [22]:
result=data.stack()

In [23]:
result

state     number
ohio      one       0
          two       1
          three     2
colorado  one       3
          two       4
          three     5
dtype: int32

In [24]:
result.unstack()

number    one  two  three
state                    
ohio        0    1      2
colorado    3    4      5

In [25]:
result.unstack(0)

state   ohio  colorado
number                
one        0         3
two        1         4
three      2         5

In [27]:
result.unstack('state')

state   ohio  colorado
number                
one        0         3
two        1         4
three      2         5

In [28]:
s1=Series([0,1,2,3],index=['a','b','c','d'])

In [31]:
s2=Series((4,5,6),index=['c','d','e'])

In [34]:
data2=pd.concat([s1,s2],keys=['one','two'])
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: int64

In [35]:
data2.unstack()

a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0

In [36]:
data2.unstack().stack()

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
two  c    4.0
     d    5.0
     e    6.0
dtype: float64

In [37]:
data2.unstack().stack(dropna=False)

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
     e    NaN
two  a    NaN
     b    NaN
     c    4.0
     d    5.0
     e    6.0
dtype: float64

In [38]:
df=DataFrame({'left':result,'right':result+5},columns=pd.Index(['left','right'],name='side'))

In [39]:
df

side             left  right
state    number             
ohio     one        0      5
         two        1      6
         three      2      7
colorado one        3      8
         two        4      9
         three      5     10

In [40]:
df.unstack('state')

side   left          right         
state  ohio colorado  ohio colorado
number                             
one       0        3     5        8
two       1        4     6        9
three     2        5     7       10

In [41]:
df.unstack('state').stack('side')

state         colorado  ohio
number side                 
one    left          3     0
       right         8     5
two    left          4     1
       right         9     6
three  left          5     2
       right        10     7