In [4]:
from sklearn import datasets;
import numpy as np;

#step1. 获取数据
iris = datasets.load_iris();#<class 'sklearn.utils.Bunch'> Bunch是一个类似于字典的键值对对象
iris_data = iris['data'];
iris_target = iris['target'];
iris_target_names = iris['target_names'];
iris_feature_names = iris['feature_names'];

print(iris_data[0:3]);
print(iris_target[0:3]);
print(iris_target_names);
print(iris_feature_names);

print(type(iris));
print(type(iris_data));
print(type(iris_target));

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]]
[0 0 0]
['setosa' 'versicolor' 'virginica']
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
<class 'sklearn.utils.Bunch'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [11]:
#step2.分割数据集
from sklearn.model_selection import train_test_split;
from sklearn import metrics;
X_train,X_test,y_train,y_test = train_test_split(iris_data,iris_target,test_size=0.2,random_state=0);
print(X_train[0:2]);
print(X_test[0:2]);
print(y_train[0:2]);
print(y_test[0:2]);

[[ 6.4  3.1  5.5  1.8]
 [ 5.4  3.   4.5  1.5]]
[[ 5.8  2.8  5.1  2.4]
 [ 6.   2.2  4.   1. ]]
[2 1]
[2 1]


In [31]:
#step3.选择对应的分类器进行训练
from sklearn import neighbors;

knn = neighbors.KNeighborsClassifier(n_neighbors=5);

#训练，大部分的算法通过调用fit方法之后，会生成一个用于以后预测结果的函数
knn.fit(X_train,y_train);

#往分类器的predict(预测)方法中传入要预测的样本X特征，返回预测结果
y_test_pred = knn.predict(X_test);
print(y_test_pred[0:3]);

[2 1 0]


In [32]:
#step4.算法的评估
print(metrics.accuracy_score(y_test,y_test_pred));


0.966666666667
