In [4]:
#1.获取数据
from sklearn import datasets
import numpy as np
digits = datasets.load_digits()
digits_data = digits['data']
digits_images = digits['images']
digits_target = digits['target']
digits_target_names = digits['target_names']
print(digits_data[0:2]);
print(digits_images[0:1]);
print(digits_target[0:3]);
print(digits_target_names[0:3]);


[[  0.   0.   5.  13.   9.   1.   0.   0.   0.   0.  13.  15.  10.  15.
    5.   0.   0.   3.  15.   2.   0.  11.   8.   0.   0.   4.  12.   0.
    0.   8.   8.   0.   0.   5.   8.   0.   0.   9.   8.   0.   0.   4.
   11.   0.   1.  12.   7.   0.   0.   2.  14.   5.  10.  12.   0.   0.
    0.   0.   6.  13.  10.   0.   0.   0.]
 [  0.   0.   0.  12.  13.   5.   0.   0.   0.   0.   0.  11.  16.   9.
    0.   0.   0.   0.   3.  15.  16.   6.   0.   0.   0.   7.  15.  16.
   16.   2.   0.   0.   0.   0.   1.  16.  16.   3.   0.   0.   0.   0.
    1.  16.  16.   6.   0.   0.   0.   0.   1.  16.  16.   6.   0.   0.
    0.   0.   0.  11.  16.  10.   0.   0.]]
[[[  0.   0.   5.  13.   9.   1.   0.   0.]
  [  0.   0.  13.  15.  10.  15.   5.   0.]
  [  0.   3.  15.   2.   0.  11.   8.   0.]
  [  0.   4.  12.   0.   0.   8.   8.   0.]
  [  0.   5.   8.   0.   0.   9.   8.   0.]
  [  0.   4.  11.   0.   1.  12.   7.   0.]
  [  0.   2.  14.   5.  10.  12.   0.   0.]
  [  0.   0.   6.  13.  10.  

In [6]:
#2.划分数据集
from sklearn.model_selection import train_test_split
from sklearn import metrics
x_train,x_test,y_train,y_test = train_test_split(digits_data,digits_target,test_size=0.2,random_state=0)
print(x_train[0:2])
print(x_test[0:2])
print(y_train[0:2])
print(y_test[0:2])

[[  0.   0.   0.   9.  15.   2.   0.   0.   0.   0.   5.  16.  11.   1.
    0.   0.   0.   0.  13.  15.   1.   0.   0.   0.   0.   2.  16.  11.
    0.   0.   0.   0.   0.   2.  16.  11.   4.   4.   0.   0.   0.   2.
   15.  16.  16.  14.  10.   1.   0.   0.   9.  16.   7.   3.  15.   6.
    0.   0.   0.   7.  15.  16.  16.   6.]
 [  0.   3.  12.  12.  14.   4.   0.   0.   0.   1.  13.   4.   4.   0.
    0.   0.   0.   4.  14.   4.   3.   0.   0.   0.   0.   5.  13.  12.
   14.  10.   0.   0.   0.   0.   0.   0.   0.  11.   6.   0.   0.   0.
    0.   0.   0.   4.   8.   0.   0.   0.   6.   2.   0.   8.   8.   0.
    0.   2.  13.  16.  16.  16.   2.   0.]]
[[  0.   0.  11.  16.  15.   3.   0.   0.   0.   5.  16.  12.  11.  13.
    0.   0.   0.   3.  13.   1.   5.  15.   0.   0.   0.   0.   0.   0.
   12.  11.   0.   0.   0.   0.   0.   1.  16.   7.   0.   0.   0.   0.
    0.  10.  15.   0.   0.   0.   0.   0.  12.  16.  16.  11.   1.   0.
    0.   0.  13.  13.   8.  13.  16.   8.]
 [  0.

In [9]:
#3.训练并预测
from sklearn import neighbors
knn = neighbors.KNeighborsClassifier(n_neighbors = 4)
knn.fit(x_train,y_train)
y_test_pred = knn.predict(x_test)
print(y_test_pred[0:5])

[2 8 2 6 6]


In [10]:
#4.评估
print(metrics.accuracy_score(y_test,y_test_pred))

0.975
